name: Sync and merge upstream repository with your current repository
description: Syncs and merges your current repository with the upstream repository. Fork of https://github.com/mheene/sync-upstream-repo.
author: Dabreadman

inputs:
  upstream_repo_url:
    description: URL of GitHub public upstream repo
    required: true
  upstream_branch:
    description: Branch to merge from upstream (defaults to downstream branch)
    required: false
    default: "main"
  downstream_repo_url:
    description: URL of the GitHub repo from upstream
    required: true
  downstream_branch:
    description: Branch to merge into downstream, if not provided it will default to the upstream branch name
    required: false
    default: ""
  token:
    description: GitHub Bot token
    required: true
  fetch_args:
    description: Git fetch arguments
    required: false
    default: ""
  rebase_args:
    description: Git rebase arguments
    required: false
    default: ""
  push_args:
    description: Git push arguments
    required: false
    default: ""

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.upstream_repo }}
    - ${{ inputs.upstream_branch }}
    - ${{ inputs.downstream_repo }}
    - ${{ inputs.downstream_branch }}
    - ${{ inputs.token }}
    - ${{ inputs.fetch_args }}
    - ${{ inputs.rebase_args }}
    - ${{ inputs.push_args }}

branding:
  icon: "git-merge"
  color: "blue"
